In [1]:
%matplotlib inline
import pandas as pd

Matplotlib is building the font cache; this may take a moment.

In [2]:
from IPython.core.display import HTML
css = open('style-table.css').read() + open('style-notebook.css').read()
HTML('<style>{}</style>'.format(css))

In [3]:
titles = pd.read_csv('data/titles.csv')
titles.head()

                                               title  year
0                                  Fight and Revenge  1997
1  Royal Shakespeare Company: The Merchant of Venice  2015
2                                     A Doll's House  1917
3                                        Shankar IPS  2010
4                                      Iki basli dev  1990

In [4]:
cast = pd.read_csv('data/cast.csv')
cast.head()

                  title  year      name   type                character     n
0        Closet Monster  2015  Buffy #1  actor                  Buffy 4  31.0
1       Suuri illusioni  1985    Homo $  actor                   Guests  22.0
2   Battle of the Sexes  2017   $hutter  actor          Bobby Riggs Fan  10.0
3  Secret in Their Eyes  2015   $hutter  actor          2002 Dodger Fan   NaN
4            Steve Jobs  2015   $hutter  actor  1988 Opera House Patron   NaN

### How many movies are listed in the titles dataframe?

In [5]:
len(titles)

226013

### What are the earliest two films listed in the titles dataframe?

In [8]:
titles.nsmallest(2, 'year')

                     title  year
96544           Miss Jerry  1894
131230  The Startled Lover  1898

In [10]:
titles.sort_values('year').head(2)

                     title  year
96544           Miss Jerry  1894
131230  The Startled Lover  1898

### How many movies have the single-word title "Hamlet"?

In [16]:
len(titles[titles['title']=='Hamlet'])

20

In [19]:
len(titles[titles.title == "Hamlet"])

20

### How many movies are titled "North by Northwest"?

### When was the first movie titled "Hamlet" made?

### List all of the "Treasure Island" movies from earliest to most recent.

### How many movies were made in the year 1950?

### How many movies were made in the year 1960?

### How many movies were made from 1950 through 1959?

### In what years has a movie titled "Batman" been released?

### How many roles were there in the movie "Inception"?

### How many roles in the movie "Inception" are NOT ranked by an "n" value?

### But how many roles in the movie "Inception" did receive an "n" value?

### Display the cast of "North by Northwest" in their correct "n"-value order, ignoring roles that did not earn a numeric "n" value.

### Display the entire cast, in "n"-order, of the 1972 film "Sleuth".

### Now display the entire cast, in "n"-order, of the 2007 version of "Sleuth".

### How many roles were credited in the silent 1921 version of Hamlet?

### How many roles were credited in Branagh’s 1996 Hamlet?

### How many "Hamlet" roles have been listed in all film credits through history?

### How many people have played an "Ophelia"?

### How many people have played a role called "The Dude"?

### How many people have played a role called "The Stranger"?

### How many roles has Sidney Poitier played throughout his career?

### How many roles has Judi Dench played?

### List the supporting roles (having n=2) played by Cary Grant in the 1940s, in order by year.

### List the leading roles that Cary Grant played in the 1940s in order by year.

### How many roles were available for actors in the 1950s?

### How many roles were available for actresses in the 1950s?

### How many leading roles (n=1) were available from the beginning of film history through 1980?

### How many non-leading roles were available through from the beginning of film history through 1980?

### How many roles through 1980 were minor enough that they did not warrant a numeric "n" rank?