In [11]:
%matplotlib inline
import pandas as pd

In [12]:
from IPython.core.display import HTML
css = open('style-table.css').read() + open('style-notebook.css').read()
HTML('<style>{}</style>'.format(css))

In [13]:
titles = pd.read_csv('data/titles.csv')
titles.head()

                                               title  year
0                                  Fight and Revenge  1997
1  Royal Shakespeare Company: The Merchant of Venice  2015
2                                     A Doll's House  1917
3                                        Shankar IPS  2010
4                                      Iki basli dev  1990

In [14]:
cast = pd.read_csv('data/cast.csv')
cast.head()

                  title  year      name   type                character     n
0        Closet Monster  2015  Buffy #1  actor                  Buffy 4  31.0
1       Suuri illusioni  1985    Homo $  actor                   Guests  22.0
2   Battle of the Sexes  2017   $hutter  actor          Bobby Riggs Fan  10.0
3  Secret in Their Eyes  2015   $hutter  actor          2002 Dodger Fan   NaN
4            Steve Jobs  2015   $hutter  actor  1988 Opera House Patron   NaN

### How many movies are listed in the titles dataframe?

In [5]:
len(titles)

226013

### What are the earliest two films listed in the titles dataframe?

In [8]:
titles.nsmallest(2, 'year')

                     title  year
96544           Miss Jerry  1894
131230  The Startled Lover  1898

In [10]:
titles.sort_values('year').head(2)

                     title  year
96544           Miss Jerry  1894
131230  The Startled Lover  1898

### How many movies have the single-word title "Hamlet"?

In [16]:
len(titles[titles['title']=='Hamlet'])

20

In [19]:
len(titles[titles.title == "Hamlet"])

20

### How many movies are titled "North by Northwest"?

In [8]:
len(titles[titles['title']=='North by Northwest'])

1

### When was the first movie titled "Hamlet" made?

In [22]:
titles[titles.title == 'Hamlet'].sort_values('year').head(1)['year'].item()

1910

In [19]:
titles[titles.title == 'Hamlet'].nsmallest(1, 'year')['year'].item()

1910

### List all of the "Treasure Island" movies from earliest to most recent.

In [24]:
titles[titles.title == 'Treasure Island'].sort_values('year')

                  title  year
82481   Treasure Island  1918
53779   Treasure Island  1920
150278  Treasure Island  1934
83513   Treasure Island  1950
55317   Treasure Island  1972
188955  Treasure Island  1973
155451  Treasure Island  1985
137881  Treasure Island  1999

### How many movies were made in the year 1950?

In [27]:
len(titles[titles.year == 1950])

1109

### How many movies were made in the year 1960?

In [29]:
len(titles[titles.year == 1960])

1496

### How many movies were made from 1950 through 1959?

In [40]:
t = titles 
len(t[(t.year >= 1950) & (t.year <= 1959)])

12664

### In what years has a movie titled "Batman" been released?

In [45]:
t[t.title == "Batman"]['year'].tolist()

[1989, 1943]

### How many roles were there in the movie "Inception"?

In [46]:
c = cast

In [51]:
len(c[c.title == 'Inception']['character'].unique())

56

In [52]:
# How many roles were there in the movie "Inception"?

c = cast
len(c[c.title == 'Inception'])

78

### How many roles in the movie "Inception" are NOT ranked by an "n" value?

In [18]:
c = cast
c = c[c.title == "Inception"]
len(c[c.n.isnull()])

27

### But how many roles in the movie "Inception" did receive an "n" value?

In [22]:
c = cast
c = c[c.title == "Inception"]
len(c[c.n > 0])

51

In [24]:
c = cast
c = c[c.title == "Inception"]
len(c[c.n.notnull()])

51

### Display the cast of "North by Northwest" in their correct "n"-value order, ignoring roles that did not earn a numeric "n" value.

In [28]:
c = cast
c = c[c.title == "North by Northwest"]
c[c.n.notnull()].sort_values('n')

,title,year,name,type,character,n
797150,North by Northwest,1959,Cary Grant,actor,Roger O. Thornhill,1.0
3201980,North by Northwest,1959,Eva Marie Saint,actress,Eve Kendall,2.0
1333732,North by Northwest,1959,James Mason,actor,Phillip Vandamm,3.0
2878461,North by Northwest,1959,Jessie Royce Landis,actress,Clara Thornhill,4.0
326415,North by Northwest,1959,Leo G. Carroll,actor,The Professor,5.0
2780220,North by Northwest,1959,Josephine Hutchinson,actress,Mrs. Townsend,6.0
1551491,North by Northwest,1959,Philip Ober,actor,Lester Townsend,7.0
1167105,North by Northwest,1959,Martin Landau,actor,Leonard,8.0
2239203,North by Northwest,1959,Adam Williams,actor,Valerian,9.0
1657968,North by Northwest,1959,Edward Platt,actor,Victor Larrabee,10.0
609229,North by Northwest,1959,Robert Ellenstein,actor,Licht,11.0
2100440,North by Northwest,1959,Les Tremayne,actor,Auctioneer,12.0
425645,North by Northwest,1959,Philip Coolidge,actor,Dr. Cross,13.0
1379980,North by Northwest,1959,Patrick McVey,actor,Sergeant Flamm,14.0
189719,North by Northwest,1959,Edward Binns,actor,Captain Junket,15.0
1267109,North by Northwest,1959,Ken Lynch,actor,Charley - Chicago Policeman,16.0

### Display the entire cast, in "n"-order, of the 1972 film "Sleuth".

In [30]:
c = cast
c = c[c.title == "Sleuth"]
c[c.year == 1972].sort_values('n')

,title,year,name,type,character,n
1560814,Sleuth,1972,Laurence Olivier,actor,Andrew Wyke,1.0
299291,Sleuth,1972,Michael Caine,actor,Milo Tindle,2.0
342151,Sleuth,1972,Alec Cawthorne,actor,Inspector Doppler,3.0
1341313,Sleuth,1972,John (II) Matthews,actor,Detective Sergeant Tarrant,4.0
2490141,Sleuth,1972,Eve (III) Channing,actress,Marguerite Wyke,5.0
1325945,Sleuth,1972,Teddy Martin,actor,Police Constable Higgs,6.0

### Now display the entire cast, in "n"-order, of the 2007 version of "Sleuth".

In [31]:
c = cast
c = c[c.title == 'Sleuth']
c = c[c.year == 2007]
c.sort_values('n')

          title  year                 name     type          character    n
299292   Sleuth  2007        Michael Caine    actor             Andrew  1.0
1183659  Sleuth  2007             Jude Law    actor               Milo  2.0
1652936  Sleuth  2007        Harold Pinter    actor        Man on T.V.  3.0
238747   Sleuth  2007      Kenneth Branagh    actor  Other Man on T.V.  NaN
342152   Sleuth  2007  Alec (II) Cawthorne    actor  Inspector Doppler  NaN
2490140  Sleuth  2007    Eve (II) Channing  actress    Marguerite Wyke  NaN
3069393  Sleuth  2007    Carmel O'Sullivan  actress             Maggie  NaN

### How many roles were credited in the silent 1921 version of Hamlet?

In [37]:
c = cast
c = c[(c.title == 'Hamlet') & (c.year == 1921)]
len(c)

9

### How many roles were credited in Branagh’s 1996 Hamlet?

In [41]:
c = cast
c = c[(c.title == 'Hamlet') & (c.year == 1996)]
len(c)

54

### How many "Hamlet" roles have been listed in all film credits through history?

In [47]:
c = cast
c = c[c.character == 'Hamlet']
len(c)

93

### How many people have played an "Ophelia"?

In [52]:
c = cast
c = c[c.character == 'Ophelia']
len(c.name.unique())

101

### How many people have played a role called "The Dude"?

In [55]:
c = cast
c = c[c.character == 'The Dude']
len(c.name.unique())

17

### How many people have played a role called "The Stranger"?

In [58]:
c = cast
c = c[c.character == 'The Stranger']
len(c.name.unique())

160

### How many roles has Sidney Poitier played throughout his career?

In [63]:
c = cast
c = c[c.name == 'Sidney Poitier']
len(c)

43

### How many roles has Judi Dench played?

In [64]:
c = cast
c = c[c.name == 'Judi Dench']
len(c)

55

### List the supporting roles (having n=2) played by Cary Grant in the 1940s, in order by year.

In [70]:
c = cast
c = c[(c.name == 'Cary Grant') & (c.year >= 1940) & (c.year <= 1949) & (c.n == 2)]
c.sort_values('year')

                   title  year        name   type    character    n
797147  My Favorite Wife  1940  Cary Grant  actor   Nick Arden  2.0
797157    Penny Serenade  1941  Cary Grant  actor  Roger Adams  2.0

In [71]:
c = cast
c = c[c.name == 'Cary Grant']
c = c[c.year // 10 == 194]
c = c[c.n == 2]
c = c.sort_values('year')
c

                   title  year        name   type    character    n
797147  My Favorite Wife  1940  Cary Grant  actor   Nick Arden  2.0
797157    Penny Serenade  1941  Cary Grant  actor  Roger Adams  2.0

### List the leading roles that Cary Grant played in the 1940s in order by year.

In [75]:
c = cast
c = c[(c.name == 'Cary Grant') & (c.year // 10 == 194) & (c.n == 1)]
c.sort_values('year')

,title,year,name,type,character,n
797172,The Howards of Virginia,1940,Cary Grant,actor,Matt Howard,1.0
797131,His Girl Friday,1940,Cary Grant,actor,Walter Burns,1.0
797174,The Philadelphia Story,1940,Cary Grant,actor,C. K. Dexter Haven,1.0
797162,Suspicion,1941,Cary Grant,actor,Johnnie Aysgarth,1.0
797176,The Talk of the Town,1942,Cary Grant,actor,Leopold Dilg,1.0
797153,Once Upon a Honeymoon,1942,Cary Grant,actor,Patrick 'Pat' O'Toole,1.0
797122,Destination Tokyo,1943,Cary Grant,actor,Capt. Cassidy,1.0
797146,Mr. Lucky,1943,Cary Grant,actor,Joe Adams -posing as Joe Bascopolous,1.0
797154,Once Upon a Time,1944,Cary Grant,actor,Jerry Flynn,1.0
797114,Arsenic and Old Lace,1944,Cary Grant,actor,Mortimer Brewster,1.0
797149,None But the Lonely Heart,1944,Cary Grant,actor,Ernie Mott,1.0
797148,Night and Day,1946,Cary Grant,actor,Cole Porter,1.0
797151,Notorious,1946,Cary Grant,actor,Devlin,1.0
797168,The Bachelor and the Bobby-Soxer,1947,Cary Grant,actor,Dick Nugent,1.0
797169,The Bishop's Wife,1947,Cary Grant,actor,Dudley,1.0
797145,Mr. Blandings Builds His Dream House,1948,Cary Grant,actor,Jim Blandings,1.0
797126,Every Girl Should Be Married,1948,Cary Grant,actor,Dr. Madison Brown,1.0
797135,I Was a Male War Bride,1949,Cary Grant,actor,Captain Henri Rochard,1.0

### How many roles were available for actors in the 1950s?

In [16]:
c = cast
c = c[c.year // 10 == 195]
c = c[c.type == 'actor']
len(c)

153559

### How many roles were available for actresses in the 1950s?

In [18]:
c = cast
c = c[(c.year // 10 == 195) & (c.type == 'actress')]
len(c)

56331

### How many leading roles (n=1) were available from the beginning of film history through 1980?

In [20]:
c = cast
c = c[c.n == 1]
c = c[c.year <= 1980]
len(c)

62763

### How many non-leading roles were available through from the beginning of film history through 1980?

In [22]:
c = cast
c = c[c.n != 1]
c = c[c.year <=1980]
len(c)

1078306

### How many roles through 1980 were minor enough that they did not warrant a numeric "n" rank?

In [24]:
c = cast
c = c[c.n.isnull()]
c = c[c.year <=1980]
len(c)

437383